/*******************************************************************************
 * DEMO PROJECT: YouSoundGreat Billing Intelligence
 * Script: 04_grants.sql
 * PURPOSE: Assign schema + warehouse privileges to demo roles.
 * OBJECTS GRANTED:
 *   - SNOWFLAKE_EXAMPLE.* schemas
 *   - Warehouse SFE_BILLING_WH
 * CLEANUP: sql/99_cleanup/teardown_all.sql
 ******************************************************************************/
USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE BILLING_ANALYST_ROLE;
GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE SFE_PIPELINE_ROLE;
GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE SFE_INTELLIGENCE_ROLE;
GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE SFE_STREAMLIT_ROLE;

GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SFE_RAW_BILLING TO ROLE SFE_PIPELINE_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SFE_STG_TELECOM TO ROLE SFE_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SNOWFLAKE_EXAMPLE.SFE_RAW_BILLING TO ROLE SFE_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SNOWFLAKE_EXAMPLE.SFE_STG_TELECOM TO ROLE SFE_PIPELINE_ROLE;
GRANT USAGE, SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE_EXAMPLE.SFE_ANALYTICS_COSTS TO ROLE BILLING_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWFLAKE_EXAMPLE.SFE_ANALYTICS_COSTS TO ROLE BILLING_ANALYST_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SFE_ANALYTICS_COSTS TO ROLE BILLING_ANALYST_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SFE_ANALYTICS_COSTS TO ROLE SFE_INTELLIGENCE_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SFE_SHARED_KNOWLEDGE TO ROLE SFE_INTELLIGENCE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWFLAKE_EXAMPLE.SFE_SHARED_KNOWLEDGE TO ROLE SFE_INTELLIGENCE_ROLE;

GRANT USAGE ON WAREHOUSE SFE_BILLING_WH TO ROLE BILLING_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE SFE_BILLING_WH TO ROLE SFE_PIPELINE_ROLE;
GRANT USAGE ON WAREHOUSE SFE_BILLING_WH TO ROLE SFE_STREAMLIT_ROLE;
GRANT USAGE ON WAREHOUSE SFE_BILLING_WH TO ROLE SFE_INTELLIGENCE_ROLE;
