/*******************************************************************************
 * DEMO PROJECT: YouSoundGreat Billing Intelligence
 * Script: teardown_all.sql
 * PURPOSE: Remove demo-specific objects without touching shared infrastructure.
 ******************************************************************************/
USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE_EXAMPLE;

-- Stop tasks before dropping
ALTER TASK IF EXISTS SFE_STG_TELECOM.SFE_PIPELINE_USAGE_TO_STG SUSPEND;
ALTER TASK IF EXISTS SFE_ANALYTICS_COSTS.SFE_PIPELINE_STG_TO_FACT SUSPEND;

-- Drop tasks and streams
DROP TASK IF EXISTS SFE_STG_TELECOM.SFE_PIPELINE_USAGE_TO_STG;
DROP TASK IF EXISTS SFE_ANALYTICS_COSTS.SFE_PIPELINE_STG_TO_FACT;
DROP STREAM IF EXISTS SFE_RAW_BILLING.USAGE_METRICS_STREAM;
DROP STREAM IF EXISTS SFE_RAW_BILLING.COST_ALLOC_STREAM;

-- Drop ML + Cortex assets
DROP SNOWFLAKE.ML.CLASSIFICATION IF EXISTS SFE_ANALYTICS_COSTS.SFE_USAGE_ANOMALY_MODEL;
DROP CORTEX SEARCH SERVICE IF EXISTS SFE_SHARED_KNOWLEDGE.SFE_BILLING_SEARCH;

-- Remove agent and Streamlit app
ALTER SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT
    DROP AGENT IF EXISTS SFE_ANALYTICS_COSTS.SFE_BILLING_AGENT;
DROP AGENT IF EXISTS SFE_ANALYTICS_COSTS.SFE_BILLING_AGENT;
DROP STREAMLIT IF EXISTS SFE_ANALYTICS_COSTS.SFE_BILLING_STREAMLIT;

-- Drop Git repo clone (keep API integration per shared use)
DROP GIT REPOSITORY IF EXISTS SNOWFLAKE_EXAMPLE.GIT_REPOS.SFE_BILLING_REPO;

-- Drop warehouse
DROP WAREHOUSE IF EXISTS SFE_BILLING_WH;

-- Drop schemas with cascade
DROP SCHEMA IF EXISTS SFE_SHARED_KNOWLEDGE CASCADE;
DROP SCHEMA IF EXISTS SFE_ANALYTICS_COSTS CASCADE;
DROP SCHEMA IF EXISTS SFE_STG_TELECOM CASCADE;
DROP SCHEMA IF EXISTS SFE_RAW_BILLING CASCADE;

-- Preserve SNOWFLAKE_EXAMPLE database and SFE_GIT_API_INTEGRATION as shared assets.
